version: '3.8'

services:
  node:
    image: node:18
    volumes:
      - .:/opt/project:cached
      - next:/opt/project/.next
      - node_modules:/opt/project/node_modules
    working_dir: /opt/project
    ports:
      - "3000:3000"
    tty: true

volumes:
 next:
 node_modules:
